{
  imports = [
    ./terminal/ghostty.nix
    ./terminal/starship.nix
    ./browser/zen.nix
    ./dev/git.nix
    ./dev/lazygit.nix
    ./dev/ssh.nix
    ./dev/git-signing-ssh.nix
    ./dev/opencode.nix
    ./core/direnv.nix
    ./desktop/waybar.nix
    ./desktop/niri.nix
    ./desktop/swaybg.nix
    ./desktop/notifications.nix
    ./desktop/polkit.nix
    ./desktop/gammastep.nix
    ./desktop/icons.nix
    ./desktop/gtk.nix
    ./desktop/darkman.nix
    ./desktop/vicinae.nix
    ./desktop/thunderbird.nix
    ./desktop/bitwarden-cli.nix
    ./desktop/i2c.nix
    ./desktop/wallust.nix
    ./desktop/swaync.nix
    ./desktop/appimages.nix
    ./desktop/discord.nix
    ./desktop/obs.nix
    ./desktop/xwayland-satellite.nix
    ./desktop/discord.nix
    ./desktop/xdg.nix
    ./desktop/showmethekey.nix
    # ./desktop/nvf.nix
    ./desktop/neovim.nix
    ./desktop/rustdesk.nix
    # ./desktop/tmux.nix
    ./shells/fish.nix
  ];
}
