{
  imports = [
    ./terminal/ghostty.nix
    ./browser/zen.nix
    ./dev/git.nix
    ./dev/lazygit.nix
    ./dev/ssh.nix
    ./dev/git-signing-ssh.nix
    ./dev/ni.nix
    ./core/direnv.nix
    ./desktop/waybar.nix
    ./desktop/niri.nix
    ./desktop/swaybg.nix
    ./desktop/notifications.nix
    ./desktop/polkit.nix
    ./desktop/gammastep.nix
    ./shells/fish.nix
  ];
}
