# Diagnostics
"hint" = { fg = "cyan500", bg = "bg", modifiers= ["bold"] }
"warning" =  { fg = "yellow500", bg = "bg", modifiers= ["bold"] }
"error" = { fg = "red", bg = "bg", modifiers= ["bold"] }
"info" = { fg = "blue", bg = "bg", modifiers= ["bold", "underlined"] }
"diff.plus" = { fg = "green" }
"diff.minus" = { fg = "red300" }
"diff.delta" = { fg = "yellow500" }

# TODO: Review this colors
"diagnostic.warning" = { underline = { style = "curl", color = "yellow500" } }
"diagnostic.error" = { underline = { style = "curl", color = "red" } }
"diagnostic.info" = { underline = { style = "curl", color = "blue" } }
"diagnostic.hint" = { underline = { style = "curl", color = "cyan500" } }
"diagnostic.unnecessary" = { modifiers = ["dim"] }
"diagnostic.deprecated" = { modifiers = ["crossed_out"] }

# Syntax highlighting
"attribute" = { fg = "blue" }
"type" = { fg = "yellow" }
"type.builtin" = { fg = "yellow" }
"type.parameter" = { fg = "yellow" }
"type.enum" = { fg = "orange500" }
"constructor" = { fg = "yellow" }
"constant" = { fg = "cyan" }
"constant.builtin" = { fg = "cyan" }
"constant.character.escape" = { fg = "orange700" }
"constant.numeric" = { fg = "cyan" }
"string" = { fg = "cyan" }
# "string.regexp" = { fg = "base0", bg = "violet" } # ?
# "string.special.path" = { fg = "violet" } # ?
# "string.special.url" = { fg = "violet" } # ?
# "string.special.symbol" = { fg = "violet" } # ?
"comment" = { fg = "base01", modifiers = ["italic"] }
"variable" = { fg = "yellow" }
"variable.builtin" = { fg = "orange500" }
"variable.parameter" = { fg = "orange500" }
"variable.other.member" = { fg = "blue" }
"variable.other.member.private" = { fg = "cyan" }
"label" = { fg = "yellow" }
"punctuation.delimiter" = { fg = "green" }
"punctuation.bracket" = { fg = "orange500" }
"punctuation.special" = { fg = "orange500" }
"keyword.control" = { fg = "green" }
"keyword.control.conditional" = { fg = "green" }
"keyword.control.repeat" = { fg = "green" }
"keyword.control.import" = { fg = "red" }
"keyword.control.return" = { fg = "green" }
"keyword.control.exception" = { fg = "green" }
"keyword.directive" = { fg = "red" }
"keyword.function" = { fg = "green" }
"keyword.storage" = { fg = "green" }
"operator" = { fg = "green" }
"function" = { fg = "blue" }
"function.method" = { fg = "blue" }
"function.method.private" = { fg = "blue" }
"function.macro" = { fg = "red500" }
"function.special" = { fg = "red500" }
"tag" = { fg = "orange" }
"namespace" = { fg = "red500" }
"special" = { fg = "orange500" }

# TODO: MARKDON
# "markup" = { fg = "violet" }
# "markup.heading" = { fg = "violet" }
# "markup.heading.marker" = { fg = "violet" }
# "markup.heading.marker.1" = { fg = "violet" }
# "markup.heading.marker.2" = { fg = "violet" }
# "markup.heading.marker.3" = { fg = "violet" }
# "markup.heading.marker.4" = { fg = "violet" }
# "markup.heading.marker.5" = { fg = "violet" }
# "markup.heading.marker.6" = { fg = "violet" }
# "markup.list" = { fg = "violet" }
# "markup.unnumbered" = { fg = "violet" }
# "markup.numbered" = { fg = "violet" }
# "markup.checked" = { fg = "violet" }
# "markup.unchecked" = { fg = "violet" }
# "markup.bold" = { fg = "violet" }
# "markup.italic" = { fg = "violet" }
# "markup.strikethrough" = { fg = "violet" }
# "markup.link" = { fg = "violet" }
# "markup.link.url" = { fg = "violet" }
# "markup.link.label" = { fg = "violet" }
# "markup.link.text" = { fg = "violet" }
# "markup.quote" = { fg = "violet" }
# "markup.raw" = { fg = "violet" }
# "markup.raw.inline" = { fg = "violet" .inline}
# "markup.raw.block" = { fg = "violet" }


# Interface
# "ui.background" = { bg = "bg" } # Comment this for transparent mode
"ui.linenr" = { fg = "yellow700" }
"ui.linenr.selected" = { fg = "orange500", modifiers = ["bold"] }
"ui.selection" = { bg = "base02" }
"ui.cursor.primary" = { fg = "base04", bg = "base0" }
"ui.cursor.match" = { fg = "base03", bg = "base00" }
"ui.menu" = { fg = "base1", bg = "base04" }
"ui.menu.selected" = { fg = "base3", bg = "base02" }
"ui.help" = { fg = "base3", bg = "base04" }
"ui.text.info" = { fg = "fg", bg = "bg" }
"ui.virtual.jump-label" = { fg = "orange500", modifiers = ["bold"] }
"ui.statusline" = { fg = "base0", bg = "base03"  }
"ui.statusline.normal" = { bg = "blue", fg = "bg", modifiers = ["bold"] }
"ui.statusline.insert" = { bg = "green", fg = "bg", modifiers = ["bold"] }
"ui.statusline.select" = { bg = "magenta700", fg = "bg", modifiers = ["bold"] }
"ui.popup" = { fg = "fg", bg = "bg" }
"ui.popup.info" = {fg = "fg", bg = "bg", modifiers = ["bold"]}
"ui.window" = { fg = "base3" }
"ui.bufferline" = { fg = "base01" }
"ui.bufferline.active" = { fg = "fg", bg = "base03" }
"ui.bufferline.background" = { fg = "fg", bg = "bg"  } # Remove bg for transparent
"ui.text.focus" = { fg = "base0", bg = "base03", modifiers = ["bold"]}
"ui.text.directory" = { fg = "blue" }
"ui.virtual.indent-guide" = { fg = "violet" }
"ui.virtual.ruler" = { bg = "base02" }


[palette]
base04 = "#00141a"
base03 = "#002d38"
base02 = "#073541"
base01 = "#586e74"
base00 = "#647a82"
base0 = "#9fabad"
base1 = "#adb8b8"
base2 = "#ede7d4"
base3 = "#fdf6e2"
base4 = "#ffffff"
yellow = "#b28600"
yellow100 = "#ffe999"
yellow300 = "#ffbf00"
yellow500 = "#b28600"
yellow700 = "#664d00"
yellow900 = "#332700"
orange = "#ca4c16"
orange100 = "#ff9166"
orange300 = "#f84f0d"
orange500 = "#ca4c16"
orange700 = "#a23c11"
orange900 = "#5c230a"
red = "#dc312e"
red100 = "#ff9b99"
red300 = "#f65351"
red500 = "#dc312e"
red700 = "#b7221f"
red900 = "#57100f"
magenta = "#d33682"
magenta100 = "#ff75b8"
magenta300 = "#f254a1"
magenta500 = "#d33682"
magenta700 = "#b02769"
magenta900 = "#541232"
violet = "#6d72c5"
violet100 = "#cccfff"
violet300 = "#9ca0ed"
violet500 = "#6d72c5"
violet700 = "#494eb6"
violet900 = "#25285b"
blue = "#278bd3"
blue100 = "#a8dbff"
blue300 = "#47adf5"
blue500 = "#278bd3"
blue700 = "#1b6498"
blue900 = "#103956"
cyan = "#2aa298"
cyan100 = "#b8fffa"
cyan300 = "#2beede"
cyan500 = "#2aa298"
cyan700 = "#1a6365"
cyan900 = "#103a3c"
green = "#859900"
green100 = "#d6ffad"
green300 = "#b7fa00"
green500 = "#859900"
green700 = "#586600"
green900 = "#2c3300"
bg = "#00141a"
bg_highlight = "#002d38"
fg = "#839495"

