# Start apps
exec-once = uwsm app -- swww-daemon
exec-once = uwsm app -- waybar
exec-once = uwsm app -- swaync
exec-once = uwsm app -- gammastep
exec-once = uwsm app -- thunderbird
exec-once = uwsm app -- discord
exec-once = uwsm app -- fcitx5
exec-once = uwsm app -- vicinae server

# Run wallpaper script on start
exec-once = ~/.dot/.config/hypr/scripts/wallpapers.sh

# Start polkit agent as user systemd service
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# Init GNOME Keyring for secrets and SSH
exec-once = gnome-keyring-daemon --start --components=secrets,ssh

# Put cursor on workspace 1 on start
exec-once = hyprctl dispatch workspace 1
