theme = "solarized_osaka"

[editor]
true-color = true
color-modes = true
line-number = "relative"
mouse = false
bufferline = "multiple"
end-of-line-diagnostics = "hint"
# rulers = [80]

[editor.file-picker]
hidden = false

[editor.inline-diagnostics]
cursor-line = "warning"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
C-s = [":write"]

[keys.normal.space]
l = [
  ":write-all",
  ":new",
  ":insert-output lazygit",
  ":buffer-close!",
  ":redraw",
  ":reload-all",
  ":set mouse false",
 ":set mouse true",
]
