theme = "ayu_dark"

[editor]
true-color = true
line-number = "relative"
mouse = false
bufferline = "multiple"
end-of-line-diagnostics = "hint"

[editor.inline-diagnostics]
cursor-line = "warning"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]

[keys.normal.space]
l = [
  ":write-all",
  ":new",
  ":insert-output lazygit",
  ":buffer-close!",
  ":redraw",
  ":reload-all",
  ":set mouse false",
  ":set mouse true",
]
